# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ri43hiq/opengl_tutorial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ri43hiq/opengl_tutorial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ri43hiq/opengl_tutorial/CMakeFiles /home/ri43hiq/opengl_tutorial/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ri43hiq/opengl_tutorial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opengl_tutorial

# Build rule for target.
opengl_tutorial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opengl_tutorial
.PHONY : opengl_tutorial

# fast build rule for target.
opengl_tutorial/fast:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/build
.PHONY : opengl_tutorial/fast

src/arcball.o: src/arcball.cpp.o

.PHONY : src/arcball.o

# target to build an object file
src/arcball.cpp.o:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/arcball.cpp.o
.PHONY : src/arcball.cpp.o

src/arcball.i: src/arcball.cpp.i

.PHONY : src/arcball.i

# target to preprocess a source file
src/arcball.cpp.i:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/arcball.cpp.i
.PHONY : src/arcball.cpp.i

src/arcball.s: src/arcball.cpp.s

.PHONY : src/arcball.s

# target to generate assembly for a file
src/arcball.cpp.s:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/arcball.cpp.s
.PHONY : src/arcball.cpp.s

src/foo.o: src/foo.cpp.o

.PHONY : src/foo.o

# target to build an object file
src/foo.cpp.o:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/foo.cpp.o
.PHONY : src/foo.cpp.o

src/foo.i: src/foo.cpp.i

.PHONY : src/foo.i

# target to preprocess a source file
src/foo.cpp.i:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/foo.cpp.i
.PHONY : src/foo.cpp.i

src/foo.s: src/foo.cpp.s

.PHONY : src/foo.s

# target to generate assembly for a file
src/foo.cpp.s:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/foo.cpp.s
.PHONY : src/foo.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.o: src/mesh.cpp.o

.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i

.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s

.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/object.o: src/object.cpp.o

.PHONY : src/object.o

# target to build an object file
src/object.cpp.o:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/object.cpp.o
.PHONY : src/object.cpp.o

src/object.i: src/object.cpp.i

.PHONY : src/object.i

# target to preprocess a source file
src/object.cpp.i:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/object.cpp.i
.PHONY : src/object.cpp.i

src/object.s: src/object.cpp.s

.PHONY : src/object.s

# target to generate assembly for a file
src/object.cpp.s:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/object.cpp.s
.PHONY : src/object.cpp.s

src/ocTree.o: src/ocTree.cpp.o

.PHONY : src/ocTree.o

# target to build an object file
src/ocTree.cpp.o:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/ocTree.cpp.o
.PHONY : src/ocTree.cpp.o

src/ocTree.i: src/ocTree.cpp.i

.PHONY : src/ocTree.i

# target to preprocess a source file
src/ocTree.cpp.i:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/ocTree.cpp.i
.PHONY : src/ocTree.cpp.i

src/ocTree.s: src/ocTree.cpp.s

.PHONY : src/ocTree.s

# target to generate assembly for a file
src/ocTree.cpp.s:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/ocTree.cpp.s
.PHONY : src/ocTree.cpp.s

src/ocTreeLeaf.o: src/ocTreeLeaf.cpp.o

.PHONY : src/ocTreeLeaf.o

# target to build an object file
src/ocTreeLeaf.cpp.o:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/ocTreeLeaf.cpp.o
.PHONY : src/ocTreeLeaf.cpp.o

src/ocTreeLeaf.i: src/ocTreeLeaf.cpp.i

.PHONY : src/ocTreeLeaf.i

# target to preprocess a source file
src/ocTreeLeaf.cpp.i:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/ocTreeLeaf.cpp.i
.PHONY : src/ocTreeLeaf.cpp.i

src/ocTreeLeaf.s: src/ocTreeLeaf.cpp.s

.PHONY : src/ocTreeLeaf.s

# target to generate assembly for a file
src/ocTreeLeaf.cpp.s:
	$(MAKE) -f CMakeFiles/opengl_tutorial.dir/build.make CMakeFiles/opengl_tutorial.dir/src/ocTreeLeaf.cpp.s
.PHONY : src/ocTreeLeaf.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... opengl_tutorial"
	@echo "... src/arcball.o"
	@echo "... src/arcball.i"
	@echo "... src/arcball.s"
	@echo "... src/foo.o"
	@echo "... src/foo.i"
	@echo "... src/foo.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/object.o"
	@echo "... src/object.i"
	@echo "... src/object.s"
	@echo "... src/ocTree.o"
	@echo "... src/ocTree.i"
	@echo "... src/ocTree.s"
	@echo "... src/ocTreeLeaf.o"
	@echo "... src/ocTreeLeaf.i"
	@echo "... src/ocTreeLeaf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

